---
### **MÔI TRƯỜNG TRIỂN KHAI ỨNG DỤNG**
---

In [1]:
## Kết nối Google Drive
from google.colab import drive
drive.mount('/content/gdrive', force_remount = True)

Mounted at /content/gdrive


# Demo 3: **Mảng và ma trận**
<u>Nội dung</u>:
1. Mảng (ARRAY)
2. Vectơ (VECTOR)
2. Ma trận (MATRIX)

<u>Cập nhật</u>: **03/2024**

In [ ]:
## Thư mục làm việc
folder = '/content/gdrive/My Drive/Colab Notebooks/DA'

In [ ]:
## Thư viện
import numpy                  as np
import scipy.spatial.distance as dist

---
### **1. Mảng (ARRAY)**
---

##### *Khởi tạo array*

In [ ]:
nrows, ncols = 3, 4
min, max = 0, 20

arr = np.array([1, 2, 3, 4, 5, 6])
print('a)', arr)
print(f'Kích thước: {len(arr):d}', f'; {arr.shape[0]:d}')
arr = np.zeros(ncols) # các phần tử = 0.0
print('b)', arr)
arr = np.ones(ncols) # các phần tử = 1.0
print('c)', arr)
arr = np.random.random(ncols) # số thực ngẫu nhiên
print('d)', arr)
arr = np.random.randint(min, max + 1, ncols) # số nguyên ngẫu nhiên
print('e)', arr)

a) [1 2 3 4 5 6]
Kích thước: 6 ; 6
b) [0. 0. 0. 0.]
c) [1. 1. 1. 1.]
d) [0.22468146 0.38075915 0.40209563 0.66441272]
e) [ 4 14 15 11]


##### *Chuyển đổi giữa array và list*

In [ ]:
## Chuyển từ list sang array
lst = [1, 2, 3]
arr = np.asarray(lst)
print('Array:', arr) # không có dấu , phân cách

## Chuyển từ array sang list
lst = arr.tolist()
print('List: ', lst)

Array: [1 2 3]
List:  [1, 2, 3]


##### *Truy cập các phần tử của array bằng chỉ số (**indexing**, **fancy indexing** - Vanderplas, p. 107)*

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print('arr[0]         =', arr[0])
print('arr[last]      =', arr[len(arr) - 1])
print('arr[3]         =', arr[3])
print('arr[-3]        =', arr[-3])
print('arr[2], arr[6] =', arr[[1, 5]])

arr[6] = '7' # thay đổi giá trị của phần tử
print('arr[]     =', arr)
print('arr[] * 2 =', arr + arr)
print('arr[] * 2 =', arr * 2)

arr[0]         = 1
arr[last]      = 10
arr[3]         = 4
arr[-3]        = 8
arr[2], arr[6] = [2 6]
arr[]     = [ 1  2  3  4  5  6  7  8  9 10]
arr[] * 2 = [ 2  4  6  8 10 12 14 16 18 20]
arr[] * 2 = [ 2  4  6  8 10 12 14 16 18 20]


##### *Truy cập các phần tử của array theo cơ chế slice (**slicing**)*

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print('Từ vị trí 3 đến 5:       ', arr[2:5])
print('Từ vị trí 3 đến cuối:    ', arr[2:])
print('Lấy 2 phần tử cuối cùng: ', arr[-2:])
print('Từ đầu đến vị trí 6:     ', arr[:6])
print('Không lấy 6 phần tử cuối:', arr[:-6])

arr[2:5] *= 2 # cập nhật nhiều phần tử
print('Sau khi cập nhật:', arr)

Từ vị trí 3 đến 5:        [3 4 5]
Từ vị trí 3 đến cuối:     [ 3  4  5  6  7  8  9 10]
Lấy 2 phần tử cuối cùng:  [ 9 10]
Từ đầu đến vị trí 6:      [1 2 3 4 5 6]
Không lấy 6 phần tử cuối: [1 2 3 4]
Sau khi cập nhật: [ 1  2  6  8 10  6  7  8  9 10]


##### *Truy cập các phần tử của array theo điều kiện (**masking**)*

In [ ]:
arr  = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
idx  = (4 < arr) & (arr % 3 == 0) # những chỉ số thỏa điều kiện
print(idx)

arr1 = arr[idx]
# arr[(4 < arr) & (arr % 3 == 0)]
print(arr1)

[False False False False False  True False False  True False]
[6 9]


In [ ]:
## Sử dụng numpy.where()
idx = np.where((4 < arr) & (arr % 3 == 0))
print(arr[idx])

[6 9]


##### *Thêm phần tử vào array*

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
new = np.append(arr, np.array([11, 12, 13])) # ghép thêm vào cuối
print(new)
new = np.insert(arr, 3, np.array([11, 12, 13])) # chèn vào vị trí thứ 4
print(new)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 1  2  3 11 12 13  4  5  6  7  8  9 10]


##### *Xóa phần tử của array*

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
new = np.delete(arr, [3, -1] ) # xoá phần tử thứ 4 và cuối cùng
print(new)

[1 2 3 5 6 7 8 9]


##### *Sắp xếp array*

In [ ]:
arr = np.random.randint(0, 6, 20)
new = np.sort(arr)
print(new)

[0 0 0 0 1 2 2 2 2 3 3 4 4 4 4 4 4 5 5 5]


##### *Thống kê số liệu trên array*

In [ ]:
arr = np.random.randint(0, 6, 20)
print(arr)
print(f'Min, Max, Mean = ({np.min(arr):.2f} {np.max(arr):.2f} {np.mean(arr):.2f})')

[5 3 4 2 0 2 0 4 3 2 2 1 1 2 0 4 1 0 2 2]
Min, Max, Mean = (0.00 5.00 2.00)


---
### **2. Vectơ (VECTOR)**
---



*   Dùng để biểu diễn cho một đối tượng trên thực tế
**Ứng dụng tích vô hướng:** Tính điểm trung bình với các môn có trọng số

***2. TÍCH VÔ HƯỚNG***
*   Tích vô hướng của hai vector cho biết mức độ tương đồng của hai vector/ của hai đối tượng đó ->  Bởi vì có cos, nếu cos tiến về 1 thì hai vector đó có sự tương đồng nhau, nếu tiến về 0 thì hai vector đó không liên quan nhau
***Ví dụ:** Để xét xem rằng hai học sinh có mức độ học tập tương đồng nhau hay không thì ta sử dụng *tích vô hướng* cho điểm của hai học sinh đó
*Sử dụng tích vô hướng để ước lượng độ tương đồng giữa khách hàng với sản phẩm để recommend cho khách hàng*

***3. CHUẨN CỦA VECTOR (Vector Norm)***

##### *Các phép toán trên vectơ*

In [ ]:
v1 = np.array([1, 3, 5, 7])
v2 = np.array([2, 4, 6, 8])

# Tổng 2 vectơ, tích vectơ với vô hướng
print('v1 + v2    =', v1 + v2)
print('v1 * alpha =', v1 * 5)

# Tích vô hướng
print(f'Tích vô hướng: {(v1 @ v2):.2f}, {v1.dot(v2):.2f}')

# Chuẩn vectơ
print('Norm L1:  ', np.linalg.norm(v1, 1))
print('Norm L2:  ', np.linalg.norm(v1, 2))
print('Norm Lmax:', np.linalg.norm(v1, np.inf))

v1 + v2    = [ 3  7 11 15]
v1 * alpha = [ 5 15 25 35]
Tích vô hướng: 100.00, 100.00
Norm L1:   16.0
Norm L2:   9.16515138991168
Norm Lmax: 7.0


**Khoảng cách Manhattan:** Đường đi giữa hai vector AB dọc theo hai trục -> Chi phí đi, nếu không cho đi xéo

**Khoảng cách Euclidean:** Đường nối trực tiếp giữa hai điểm này (Đường chim bay) -> Tính khoảng cách gần nhất để chọn điểm

**Khoảng cách Chebyshev:** đường đi từ A đến B nhưng cho phép đi xiên 45 độ (Độ dài con Vua trong Chessboard, đi ngang đi dọc và đi xéo 45 độ) -> Chi phí đi, nếu cho đi xéo

In [ ]:
## Đại lượng khoảng cách (từ gốc tọa độ đến ĐỈNH)
O = np.zeros(4) # gốc tọa độ
#ouput: [0.0.0.0]

## Các khoảng cách
print('Manhattan distance =', dist.cityblock(v1, v2))
print('Euclidean distance =', dist.euclidean(v1, v2))
print('Chebyshev distance =', dist.chebyshev(v1, v2))

Manhattan distance = 4
Euclidean distance = 2.0
Chebyshev distance = 1


---
### **3. Ma trận (MATRIX)**
---



*   **Bản chất của ma trận** là biểu diễn cho một tập hợp các đối tượng, trong đó mỗi dòng là một vector (thể hiện cho một đối tương), mỗi cột là một feature. Lúc này, ma trận này sẽ là một hình chữ nhật, không nhất thiết số dòng bằng số cột

*   **Bản chất của ma trận vuông** thể hiện mối quan hệ nội tại bên trong các phần tử của một tập hợp

*   Trong một ma trận, ta thay đổi vị trí các dòng, hoặc thay đổi vị trí các cột thì bản chất của bài toán/dữ liệu không thay đổi (Nhưng nếu thay đổi một ô thì khác)



##### *Khởi tạo ma trận*

In [ ]:
nrows, ncols = 3, 4
min, max, value = 0, 20, 5

mtr = np.array([[1, 2, 3], [4, 5, 6]])
print('a)\n', mtr)
print(f' Kích thước: ({mtr.shape[0]:d}, {mtr.shape[1]:d})')
mtr = np.zeros((nrows, ncols))
print('b)\n', mtr)
mtr = np.ones((nrows, ncols))
print('c)\n', mtr)
mtr = np.identity(nrows) # ma trận đơn vị
print('d)\n', mtr)
mtr = np.full((nrows, ncols), value)
print('e)\n', mtr)
mtr = np.random.randint(min, max + 1, (nrows, ncols))
print('f)\n', mtr)
mtr = np.random.random((nrows, ncols))
print('g)\n', mtr)

a)
 [[1 2 3]
 [4 5 6]]
 Kích thước: (2, 3)
b)
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
c)
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
d)
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
e)
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
f)
 [[ 3  9 19  0]
 [17 17 12 17]
 [ 3 19  1 10]]
g)
 [[0.47652146 0.86117745 0.82210582 0.92075588]
 [0.15358233 0.48570015 0.36178903 0.65566892]
 [0.88998451 0.05833642 0.52841494 0.66067175]]


##### *Truy cập các phần tử của ma trận bằng chỉ số* [row, col]

In [ ]:
# Truy cập phần tử của ma trận
mtr = np.array([[1, 2, 3], [4, 5, 6]])
mtr[1, 2] = 100
print(mtr, '\n')

# Có thể áp dụng cơ chế slice trên chỉ số dòng [row], chỉ số cột [col]
mtr = np.random.randint(min, max + 1, (4, 6))
print(mtr)

print('a) Dòng 2\n', mtr[1])
print('b) Từ dòng 2 đến dòng 3\n', mtr[1:3, :])
print('c) Dòng cuối cùng\n', mtr[-1:, :])
print('d) 2 dòng cuối\n', mtr[-2:, :])

[[  1   2   3]
 [  4   5 100]] 

[[ 8 17 19  5 18 14]
 [14 16  9  6  4 17]
 [19  8  7 14  4  0]
 [11  5 12 13 12 12]]
a) Dòng 2
 [14 16  9  6  4 17]
b) Từ dòng 2 đến dòng 3
 [[14 16  9  6  4 17]
 [19  8  7 14  4  0]]
c) Dòng cuối cùng
 [[11  5 12 13 12 12]]
d) 2 dòng cuối
 [[19  8  7 14  4  0]
 [11  5 12 13 12 12]]


##### *Rút trích những phần tử thỏa điều kiện*

In [ ]:
mtr = np.random.randint(min, max + 1, (4, 6))
print(mtr)

idx = (2 < mtr) & (mtr % 3 == 0) # những chỉ số thỏa điều kiện
new = mtr[idx]
print(new)

[[ 4 13 10  9 19  0]
 [ 4  3  9  8  4  1]
 [11 15 17  3 15  2]
 [ 2  9  3  4 20  6]]
[ 9  3  9 15  3 15  9  3  6]


##### *Các phép toán trên ma trận*



*   **Nhân hai ma trận:** (Số dòng của ma trận B phải bằng với số cột của ma trận A)


*   **Chuyển vị ma trận:** Khi chuyển vị ma trận thì bản chất của vấn đề không thay đôi
  * Ý nghĩa: Giúp thực hiện phép nhân ma trận




In [ ]:
mtr1 = np.random.randint(min, max + 1, (2, 3))
print(mtr1,'\n')
mtr2 = [[4,-1,2],
        [-2,3,1],
        [-5,2,-6]
        ]

# Các phép toán trên ma trận
print('* TỔNG 2 ma trận (mtr1 + mtr1)\n', mtr1 + mtr1)
print('* Nhân ma trận với vô hướng (5 * mtr1)\n', 5 * mtr1)
print('* TÍCH 2 ma trận (mtr1 * mtr2)\n', mtr1 @ mtr2)
print('* TÍCH 2 ma trận (mtr1 * mtr2)\n', mtr1.dot(mtr2))
print('* Chuyển vị mtr1\n', mtr1.T)
print('* Đường chéo của mtr2\n', np.diag(mtr2))
print('* Ma trận tam giác trên mtr2\n', np.triu(mtr2))
print('* Hạng của mtr2 =', np.linalg.matrix_rank(mtr2))

det = np.linalg.det(mtr2) #Định thức của ma trận 2
if det != 0:  #Điều kiện: A có ma trận nghịch đảo A-1 khi và chỉ khi |A| != 0
    print('* Ma trận nghịch đảo của mtr2\n', np.linalg.inv(mtr2))

print('* Ma trận giả nghịch đảo của mtr1\n', np.linalg.pinv(mtr1))

[[ 8  4 11]
 [ 1 11 10]] 

* TỔNG 2 ma trận (mtr1 + mtr1)
 [[16  8 22]
 [ 2 22 20]]
* Nhân ma trận với vô hướng (5 * mtr1)
 [[40 20 55]
 [ 5 55 50]]
* TÍCH 2 ma trận (mtr1 * mtr2)
 [[-31  26 -46]
 [-68  52 -47]]
* TÍCH 2 ma trận (mtr1 * mtr2)
 [[-31  26 -46]
 [-68  52 -47]]
* Chuyển vị mtr1
 [[ 8  1]
 [ 4 11]
 [11 10]]
* Đường chéo của mtr2
 [ 4  3 -6]
* Ma trận tam giác trên mtr2
 [[ 4 -1  2]
 [ 0  3  1]
 [ 0  0 -6]]
* Hạng của mtr2 = 3
* Ma trận nghịch đảo của mtr2
 [[ 0.48780488  0.04878049  0.17073171]
 [ 0.41463415  0.34146341  0.19512195]
 [-0.26829268  0.07317073 -0.24390244]]
* Ma trận giả nghịch đảo của mtr1
 [[ 0.0878224  -0.05958211]
 [-0.04864512  0.08504734]
 [ 0.04472739  0.01240614]]


In [ ]:
#Định thức của ma trận
mtr3 = [[4,-1,3],
        [-2,3,1],
        [-5,2,-6]]
print("Định thức của ma trận là",np.linalg.det(mtr3))

Định thức của ma trận là -30.000000000000014


##### *Chuyển đổi giữa ma trận (m, n) và array (m * n)*

In [ ]:
# Chuyển từ ma trận (m, n) sang array (m * n)
mtr = np.array([[1, 2, 3], [4, 5, 6]])
arr = mtr.flatten()
print("Chuyển từ ma trận sang array:",arr)

# Chuyển từ array sang ma trận
mtr = arr.reshape(2, 3)
print("Chuyển từ array sang ma trận (2,3) \n", mtr)
mtr = arr.reshape(3, 2)
print("Chuyển từ array sang ma trận (3,2) \n", mtr)

Chuyển từ ma trận sang array: [1 2 3 4 5 6]
Chuyển từ array sang ma trận (2,3) 
 [[1 2 3]
 [4 5 6]]
Chuyển từ array sang ma trận (3,2) 
 [[1 2]
 [3 4]
 [5 6]]


##### *Số liệu  thống kê trên ma trận*

In [ ]:
mtr = np.random.randint(min, max + 1, (nrows, ncols))
print(mtr,'\n')

# Thống kê trên toàn ma trận
print(f'Min, Max, Mean (ma trận) = ({np.min(mtr):.2f} {np.max(mtr):.2f} {np.mean(mtr):.2f})')

# Thống kê theo từng cột
print('SUM từng cột :', np.sum(mtr, axis = 0))

# Thống kê theo từng dòng
print('SUM từng dòng:', np.sum(mtr, axis = 1))

# Thống kê trên 1 dòng
print(f'Min, Max, Mean (dòng 2) = ({np.min(mtr[1]):.2f} {np.max(mtr[1]):.2f} {np.mean(mtr[1]):.2f})')

# Thống kê trên 1 cột
print(f'Min, Max, Mean (cột 2) = ({np.min(mtr[:, 1]):.2f} {np.max(mtr[:, 1]):.2f} {np.mean(mtr[:, 1]):.2f})')

[[11 14 18 17]
 [ 3  3 20 18]
 [ 1 11 20 14]] 

Min, Max, Mean (ma trận) = (1.00 20.00 12.50)
SUM từng cột : [15 28 58 49]
SUM từng dòng: [60 44 46]
Min, Max, Mean (dòng 2) = (3.00 20.00 11.00)
Min, Max, Mean (cột 2) = (3.00 14.00 9.33)


---
### **Giải hệ PT tuyến tính**
#### 2x - 2y + z = -3
#### x + 3y - 2z = 1
#### 3x - y - z = 2
---



*   Ứng dụng
  * Mô hình cân bằng thị trường (Market Equilibrium)
*   Phương pháp giải:
  * Phương pháp Gauss - Jordan -> Đưa ma trận mở rộng về dạng bậc thang rút gọn
  * Phương pháp khử Gauss -> Đưa ma trận mở rộng về dạng bậc thang của A
      * Bán chuẩn hóa tối đa các cột của A (Gauss)
      * Các dòng không tầm thường được xếp phía trên
      * Mỗi ma trận có nhiều Sa
      



In [ ]:
## Ma trận hệ số
A = np.array([[2, -2, 1],
              [1, 3, -2],
              [3, -1, -1]])

## Vectơ hệ số tự do
b = np.array([-3, 1, 2])

## Kiểm tra tính khả nghịch của A
print(f'det(A) = {np.linalg.det(A)}')

det(A) = -10.000000000000002


In [ ]:
## Cách giải 1: Sử dụng ma trận nghịch đảo
x = np.linalg.inv(A) @ b
print('Hệ nghiệm (x1, x2, x3) =', x)

Hệ nghiệm (x1, x2, x3) = [-1.4 -2.  -4.2]


In [ ]:
## Cách giải 2: Sử dụng hàm numpy.linalg.solve()
print('Hệ nghiệm (x1, x2) =', np.linalg.solve(A, b))

Hệ nghiệm (x1, x2) = [-1.4 -2.  -4.2]


In [ ]:
## Hệ phương trình VÔ NGHIỆM
A = np.array([[3, 2], [6, 4]])
b = np.array([5, 1])

det_A = np.linalg.det(A)
## Kiểm tra tính khả nghịch của A
print(f'det(A) = {det_A}')  # singular matrix

## Áp dụng định lý Kronecker – Capelli
rank_A = np.linalg.matrix_rank(A)
print(f'Hạng của ma trận [A] = {rank_A}')

A_B = np.array([[3, 2, 5], [6, 4, 1]])
rank_AB = np.linalg.matrix_rank(A_B)
print(f'Hạng của dạng mở rộng [A|B] = {rank_AB}')

if (det_A == 0):
    if (rank_AB == rank_A):
        print('Hệ phương trình VÔ ĐỊNH (vô số nghiệm)')
    else:
        print('Hệ phương trình VÔ NGHIỆM')

det(A) = 0.0
Hạng của ma trận [A] = 1
Hạng của dạng mở rộng [A|B] = 2
Hệ phương trình VÔ NGHIỆM


In [ ]:
## Hệ phương trình VÔ ĐỊNH
A = np.array([[3, 2], [6, 4]])
b = np.array([5, 10])

det_A = np.linalg.det(A)
## Kiểm tra tính khả nghịch của A
print(f'det(A) = {det_A}')  # singular matrix

## Áp dụng định lý Kronecker – Capelli
rank_A = np.linalg.matrix_rank(A)
print(f'Hạng của ma trận [A] = {rank_A}')

A_B = np.array([[3, 2, 5], [6, 4, 10]])
rank_AB = np.linalg.matrix_rank(A_B)
print(f'Hạng của dạng mở rộng [A|B] = {rank_AB}')

if (det_A == 0):
    if (rank_AB == rank_A):
        print('Hệ phương trình VÔ ĐỊNH (vô số nghiệm)')
    else:
        print('Hệ phương trình VÔ NGHIỆM')

det(A) = 0.0
Hạng của ma trận [A] = 1
Hạng của dạng mở rộng [A|B] = 1
Hệ phương trình VÔ ĐỊNH (vô số nghiệm)
