# DEMO 3.3: **Support Vector Machine (SVM)**
<u>Nội dung</u>:
1. Chẩn đoán bệnh ung thư
2.    

<u>Cập nhật</u>: **04/2023**




---
### **MÔI TRƯỜNG TRIỂN KHAI ỨNG DỤNG**
---

***SUPPORT VECTOR MACHINE***
*   Phân lớp SVM tuyến tính (Linear SVM Classification)
  * Xây dựng siêu phẳng (*hyperplane*) có thể phân cách các lớp
  * Để tối ưu kết quả phân lớp thì phải xác định siêu phẳng (*hyperplane*) có **khoảng cách đến các điểm dữ liệu (*margin*) của tất cả các lớp xa nhất có thể**
      * Đường hyperplane tốt nhất -> Tạo biên cực đại & Cách đều hai lớp

*   Các bước:
  1. ***Super vector (Vector hỗ trợ)***: những phần tử
đứng sát biên, gần với đối phương nhất
  2. Kẻ được hai đường biên (Pháp tuyến với vector hỗ trợ)
  3. Kẻ đường trung trực với hai đường biên đó -> Hyperplane

*  Phân lớp SVM tuyến tính:
  * *hard margin:* phân tách tuyến tính -> nhạy cảm với outliers
  * *soft margin:* cân đối giữa độ rộng của biên cực đại và giới hạn số lượng quan sát đã vi phạm đường biên


**NONLINEAR SVM CLASSIFICATION**
*   Dữ liệu không thể phân cách tuyến tính *-> Tạo siêu phẳng bằng cách phi tuyến*
*   Thông thường chỉ dùng hàm đa thức
*  Giải pháp bổ sung features *-> Phân cách phi tuyến*




In [1]:
## Môi trường lập trình
from google.colab import drive
drive.mount("/content/gdrive")
folder = '/content/gdrive/My Drive/Colab Notebooks/ML/Supervised Learning'

Mounted at /content/gdrive


In [2]:
## Thư viện
import joblib            as jlb
import matplotlib.pyplot as plt
import numpy             as np
import pandas            as pd
import seaborn           as sbn

from sklearn.model_selection import train_test_split
from sklearn                 import svm

---
## 1. **Chẩn đoán bệnh ung thư**
---

In [3]:
## Dữ liệu Breast Cancer
data = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/ML/Supervised Learning/Data/Breast Cancer WI.csv')
print(data.head())

   radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal_dimension_mean  ...  texture_worst  perimeter_worst  area_worst  \
0             

In [4]:
## Mô tả dữ liệu: Biến phân lớp (target variable): 'Class'
y = data['Class']

## Danh sách các features
nb_features = data.shape[1] - 1
features    = data.columns[:nb_features]
X           = data[features]
print('* Số lượng features = %2d' %nb_features)
print('  Các features:', ', '.join(features))

* Số lượng features = 30
  Các features: radius_mean, texture_mean, perimeter_mean, area_mean, smoothness_mean, compactness_mean, concavity_mean, concave points_mean, symmetry_mean, fractal_dimension_mean, radius_se, texture_se, perimeter_se, area_se, smoothness_se, compactness_se, concavity_se, concave points_se, symmetry_se, fractal_dimension_se, radius_worst, texture_worst, perimeter_worst, area_worst, smoothness_worst, compactness_worst, concavity_worst, concave points_worst, symmetry_worst, fractal_dimension_worst


In [5]:
## Kích thước các lớp
print("Số trường hợp CÓ    bệnh (Malignant):", y[y == 'Malignant'].size)
print("Số trường hợp KHÔNG bệnh (Benign)   :", y[y == 'Benign'].size)

Số trường hợp CÓ    bệnh (Malignant): 212
Số trường hợp KHÔNG bệnh (Benign)   : 357


In [6]:
## Chia tập dữ liệu thành training, test sets theo tỷ lệ 80:20
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2, random_state = 1)

In [7]:
##------------------------------------------------------------------------------
## Xây dựng mô hình
##------------------------------------------------------------------------------
model = svm.SVC(kernel = 'linear')
model.fit(X_train, y_train)

SVC(kernel='linear')

In [9]:
## Predict
model.predict([X_test.iloc[0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array(['Benign'], dtype=object)

In [12]:
## get support vectors
model.support_vectors_

array([[1.684e+01, 1.946e+01, 1.084e+02, ..., 8.436e-02, 2.527e-01,
        5.972e-02],
       [1.571e+01, 1.393e+01, 1.020e+02, ..., 1.374e-01, 2.723e-01,
        7.071e-02],
       [1.499e+01, 2.211e+01, 9.753e+01, ..., 1.308e-01, 3.163e-01,
        9.251e-02],
       ...,
       [1.176e+01, 1.814e+01, 7.500e+01, ..., 7.160e-02, 1.978e-01,
        6.915e-02],
       [1.448e+01, 2.146e+01, 9.425e+01, ..., 1.225e-01, 3.020e-01,
        6.846e-02],
       [1.386e+01, 1.693e+01, 9.096e+01, ..., 1.654e-01, 3.630e-01,
        1.059e-01]])

In [13]:
## get indices of support vectors
model.support_

array([ 13,  23,  25,  30,  59,  78,  96, 101, 120, 124, 149, 156, 158,
       164, 174, 181, 190, 216, 219, 297, 300, 386, 412, 423,  39,  49,
        86,  88,  91,  94, 115, 121, 125, 142, 148, 162, 227, 240, 269,
       283, 315, 360, 413, 435, 438], dtype=int32)

In [15]:
## get number of support vectors from each class
model.n_support_

array([24, 21], dtype=int32)

In [19]:
## Lưu trữ mô hình để khai thác về sau
jlb.dump(model,'/content/gdrive/My Drive/Colab Notebooks/ML/Supervised Learning/Data/Breast Cancer.svm')

['/content/gdrive/My Drive/Colab Notebooks/ML/Supervised Learning/Data/Breast Cancer.svm']

In [20]:
## Khai thác mô hình đã được huấn luyện để đoán (Test set)
model  = jlb.load('/content/gdrive/My Drive/Colab Notebooks/ML/Supervised Learning/Data/Breast Cancer.svm')

tiep = 'C'
while (tiep.upper() == 'C'):
    idx    = int(eval(input(f'Nhập chỉ số dòng từ 0 đến {X_test.shape[0]}: ')))
    idx    = idx % X_test.shape[0]
    X_new  = X_test[idx:idx + 1]
    y_pred = model.predict(X_new)
    print('Mẫu', X_new.to_string())
    print('Mẫu được dự đoán là', 'CÓ bệnh' if y_pred == 'Malignant' else 'KHÔNG có bệnh')
    tiep = input('Tiếp tục (C/K) ? ')

Nhập chỉ số dòng từ 0 đến 114: 5
Mẫu      radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  compactness_mean  concavity_mean  concave points_mean  symmetry_mean  fractal_dimension_mean  radius_se  texture_se  perimeter_se  area_se  smoothness_se  compactness_se  concavity_se  concave points_se  symmetry_se  fractal_dimension_se  radius_worst  texture_worst  perimeter_worst  area_worst  smoothness_worst  compactness_worst  concavity_worst  concave points_worst  symmetry_worst  fractal_dimension_worst
132        16.16         21.54           106.2      809.8           0.1008            0.1284          0.1043              0.05613          0.216                 0.05891     0.4332       1.265         2.844    43.68       0.004877         0.01952       0.02219           0.009231      0.01535              0.002373         19.47          31.68            129.7      1175.0            0.1395             0.3055           0.2992                0.1312           0.348           