## **BT thực hành 2.1.1: LU Decomposition**


> <u>Cập nhật</u>: **10/2023**



In [ ]:
## Thư viện
import numpy       as np
import scipy
import warnings
warnings.filterwarnings('ignore')

from scipy.linalg  import det, lu

---
## **Yêu cầu 1: Phân rã ma trận VUÔNG**
- Tạo ma trận A(4x4) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
- Phân tích thành các thành phần P, L, U. In kết quả
- Tái tạo ma trận B từ các thành phần P, L, U.
---


In [ ]:
## Tạo ma trận VUÔNG A(4, 4) với các giá trị ngẫu nhiên từ 1 đến 10
m, n, min, max = 4, 4, 1, 10
A = np.random.randint(min, max + 1, (m, n))
A

array([[ 3,  5,  1,  8],
       [ 3,  5,  2, 10],
       [ 8,  1,  9, 10],
       [ 3,  4, 10,  2]])

In [ ]:
## Phân tích A thành các thành phần P, L, U
P, L, U = lu(A)

In [ ]:
print('Ma trận HOÁN VỊ P', P.shape, ':\n', P)
print('Ma trận L', L.shape, ':\n', L)
print('Ma trận U', U.shape, ':\n', U)

Ma trận HOÁN VỊ P (4, 4) :
 [[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
Ma trận L (4, 4) :
 [[ 1.          0.          0.          0.        ]
 [ 0.375       1.          0.          0.        ]
 [ 0.375       0.78378378  1.          0.        ]
 [ 0.375       1.         -0.12982456  1.        ]]
Ma trận U (4, 4) :
 [[ 8.          1.          9.         10.        ]
 [ 0.          4.625      -1.375       6.25      ]
 [ 0.          0.          7.7027027  -6.64864865]
 [ 0.          0.          0.         -2.86315789]]


In [ ]:
## Tái tạo ma trận A từ các thành phần: A = P @ L @ U
print('Tái tạo A từ P, L, U (kiểm chứng phép phân rã):\n', (P @ L @ U).astype(int))

Tái tạo A từ P, L, U (kiểm chứng phép phân rã):
 [[ 3  5  0  8]
 [ 3  5  2 10]
 [ 8  1  9 10]
 [ 3  4 10  2]]


---
## **Yêu cầu 2: Phân rã ma trận HÌNH CHỮ NHẬT**
---

In [ ]:
## Tạo ma trận HÌNH CHỮ NHẬT
A = np.array([[1, 2,  4, 3],
              [3, 8, 14, 0],
              [2, 6, 13, 2]])

## Phân tích A thành các thành phần P, L, U
P, L, U = lu(A)

print('Ma trận HOÁN VỊ P', P.shape, ':\n', P)
print('Ma trận L', L.shape, ':\n', L)
print('Ma trận U', U.shape, ':\n', U)

print('Tái tạo A từ P, L, U (kiểm chứng phép phân rã):\n', (P @ L @ U).astype(int))

Ma trận HOÁN VỊ P (3, 3) :
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Ma trận L (3, 3) :
 [[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 0.33333333 -1.          1.        ]]
Ma trận U (3, 4) :
 [[ 3.          8.         14.          0.        ]
 [ 0.          0.66666667  3.66666667  2.        ]
 [ 0.          0.          3.          5.        ]]
Tái tạo A từ P, L, U (kiểm chứng phép phân rã):
 [[ 1  2  4  2]
 [ 3  8 14  0]
 [ 2  6 13  2]]


In [ ]:
## Tạo ma trận SUY BIẾN (det(A))= 0)
A = np.array([[1, 2],
              [2, 4]])
print(det(A))

## Phân tích A thành các thành phần P, L, U
P, L, U = lu(A)

print('Ma trận HOÁN VỊ P', P.shape, ':\n', P)
print('Ma trận L', L.shape, ':\n', L)
print('Ma trận U', U.shape, ':\n', U)

print('Tái tạo A từ P, L, U (kiểm chứng phép phân rã):\n', (P @ L @ U).astype(int))

0.0
Ma trận HOÁN VỊ P (2, 2) :
 [[0. 1.]
 [1. 0.]]
Ma trận L (2, 2) :
 [[1.  0. ]
 [0.5 1. ]]
Ma trận U (2, 2) :
 [[2. 4.]
 [0. 0.]]
Tái tạo A từ P, L, U (kiểm chứng phép phân rã):
 [[1 2]
 [2 4]]
