## **BT thực hành 2.1.4: QR Decomposition**
- Tạo ma trận A(4x5) chứa các giá trị ngẫu nhiên trong khoảng 5 - 10
- Phân tích thành các thành phần Q, R. In kết quả
- Tái tạo ma trận A từ các thành phần Q, R.


> <u>Cập nhật</u>: **10/2023**



In [ ]:
## Thư viện
import numpy        as np
import warnings
warnings.filterwarnings('ignore')

from   numpy.linalg import qr

In [ ]:
## Tạo ma trận A(4, 5) với các giá trị ngẫu nhiên từ 1 đến 10
m, n, min, max = 4, 5, 1, 10
A = np.random.randint(min, max + 1, (m, n))
print('Ma trận A(', A.shape, ':\n', A)

Ma trận A( (4, 5) :
 [[5 9 3 9 8]
 [5 1 6 4 1]
 [5 8 4 2 6]
 [9 2 5 8 7]]


In [ ]:
## Phân rã Q, R
## Các giá trị tham số
##     mode = 'reduced', 'complete': Q, R with dimensions (m, m), (m, n) (default)
Q, R = qr(A)

In [ ]:
## Ma trận vuông trực chuẩn Q
print('Ma trận Q(', Q.shape, ':\n', Q)

Ma trận Q( (4, 4) :
 [[-0.40032038  0.63854483  0.15188986 -0.63947913]
 [-0.40032038 -0.2837977  -0.83979939 -0.23224864]
 [-0.40032038  0.52325201 -0.18748354  0.7285608 ]
 [-0.72057669 -0.4877773   0.48632949  0.07953721]]


In [ ]:
## Kiểm chứng tính trực giao của Q
print(np.rint(Q @ Q.T).astype(int)) # rint(): làm tròn số

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
## Ma trận tam giác trên R
print('Ma trận R(', R.shape, ':\n', R)

Ma trận R( (4, 5) :
 [[-12.489996    -8.64692031  -8.80704846 -11.7694193  -11.04884261]
 [  0.           8.67356727  -0.13303017   1.75599828   4.54963191]
 [  0.           0.          -2.90141352   1.52347998   2.65472465]
 [  0.           0.           0.          -4.5908875   -0.41995644]]


In [ ]:
## Tái tạo A từ các thành phần Q, R (kiểm chứng lại phép phân rã)
print(np.rint(Q @ R).astype(int))

[[5 9 3 9 8]
 [5 1 6 4 1]
 [5 8 4 2 6]
 [9 2 5 8 7]]
