## **BT thực hành 2.1.3: Giải hệ PT tuyến tính dựa trên phân rã LU**


> <u>Cập nhật</u>: **10/2023**



In [2]:
## Thư viện
import numpy      as np
import scipy
import warnings
warnings.filterwarnings('ignore')

from scipy.linalg import lu, inv

In [ ]:
## Ma trận hệ số A và vector hệ số tự do B
A = np.array([[1, 2, 4],
              [3, 8, 14],
              [2, 6, 13]])
B = np.array([3, 13, 4])
print(A)
print(B)

[[ 1  2  4]
 [ 3  8 14]
 [ 2  6 13]]
[ 3 13  4]


In [ ]:
## Tìm nghiệm bằng ma trận nghịch đảo
X = inv(A) @ B
X

array([ 3.,  4., -2.])

In [ ]:
## Áp dụng phân rã LU
P, L, U = lu(A)

In [ ]:
## Kiểm chứng phép phân rã
(P @ L @ U).astype(int)

array([[ 1,  2,  4],
       [ 3,  8, 14],
       [ 2,  6, 13]])

In [ ]:
## B1. Giải L.Y = P.T @ B
Y = inv(L) @ P.T @ B
Y

array([13.        , -4.66666667, -6.        ])

In [ ]:
## B2. Giải U.X = Y
X = inv(U) @ Y
X

array([ 3.,  4., -2.])

In [3]:
#Tạo ma trận A gần 100 dòng, 100 cột
A = np.random.rand(100, 100)

#Tạo vector ngẫu nhiên gồm 100 phần tử
b = np.random.rand(100)

In [4]:
x = inv(A)@b
x

array([-0.41935512,  0.67525991, -0.17640485, -0.95432642, -0.70810251,
       -0.22985422,  1.27672898,  0.74882659, -0.76708026, -1.15665218,
        0.19178758, -0.28758888,  0.9125262 ,  0.25921944, -0.22578148,
        0.66956084,  0.32926991,  0.32707966,  0.06256545, -0.10101706,
       -0.58663713, -0.16217666, -1.14789255, -0.09187487, -0.52616383,
       -1.641459  ,  0.18924892,  0.430341  , -0.77269393, -0.07490862,
        1.04538602, -0.52494851,  1.4835759 , -0.49019143,  1.5424443 ,
       -0.08811945, -0.16269642, -0.3059306 , -0.83662026,  0.33541121,
        0.54867673, -0.75018591, -0.6916193 ,  0.20398044, -0.03326297,
       -0.20161167,  0.27572782,  0.47917735,  1.50024648,  0.32599072,
       -0.63343669,  0.97622087,  1.96563037,  0.18236566,  0.52108064,
       -0.39424099,  0.87467526,  0.85252221,  0.46556262,  0.35339265,
       -0.08660317, -0.82500033, -0.6086967 ,  0.29528198, -0.85439471,
        0.42016008, -0.27062708, -1.22062138, -0.52797092, -0.84