##**BT thực hành 2.2.2: Eigenvalues và eigenvectors của ma trận ĐỐI XỨNG**


> Cập nhật: **11/2023**



In [ ]:
import numpy      as np
import warnings
warnings.filterwarnings('ignore')

from numpy.linalg import eig, inv
from numpy        import diag

In [ ]:
## Tạo ma trận A(5 x 5) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
m, n, min, max = 5, 5, 1, 10
A = np.random.randint(min, max + 1, (m, n))
print('Ma trận A', A.shape, ':\n', A)

Ma trận A (5, 5) :
 [[ 1  1  4  4  5]
 [ 2 10  1  9  2]
 [ 4  8  2  1  7]
 [ 2 10  4  2  8]
 [ 9  8  3  1 10]]


In [ ]:
## Tạo ma trận đối xứng  P = A @ A.T
##Nếu có ma trận đối xứng thì trị riêng (nghiệm) luôn luôn có nghiệm thực
P = A @ A.T
P

array([[ 59,  62,  59,  76,  83],
       [ 62, 190, 113, 142, 130],
       [ 59, 113, 134, 154, 177],
       [ 76, 142, 154, 188, 192],
       [ 83, 130, 177, 192, 255]])

In [ ]:
## Tìm eigenvalues và eigenvectors của P
values, vectors = eig(P)

In [ ]:
## Hiển thị kết quả: Trị riêng lambda(r: số thực, i: số phức)
for j in range(len(values)):
    eigenvalue = values[j]

    r = values[j].real
    i = values[j].imag
    print('Eigenvalue[%1d]' %j, '= (%f,' %r, '%f)' %i)

print('\nEigenvectors', vectors.shape, ':\n', vectors)

Eigenvalue[0] = (686.875910, 0.000000)
Eigenvalue[1] = (91.749419, 0.000000)
Eigenvalue[2] = (0.159886, 0.000000)
Eigenvalue[3] = (28.016781, 0.000000)
Eigenvalue[4] = (19.198005, 0.000000)

Eigenvectors (5, 5) :
 [[-0.21956426 -0.0221886  -0.16096302 -0.95671224  0.10045799]
 [-0.42112217 -0.84850333  0.02970328  0.14136599  0.2860622 ]
 [-0.43429112  0.1601253  -0.83915273  0.21773042 -0.1848439 ]
 [-0.50779262  0.00809615  0.42107496 -0.03332829 -0.75077707]
 [-0.57270021  0.50382943  0.30286497  0.12727938  0.55699473]]


---
#### **Nhận xét:**
- Ma trận ĐỐI XỨNG có các giá trị riêng đều là SỐ THỰC !
---

In [ ]:
## Tái tạo P từ các eigenvectors và eigenvalues: P = B @ Lambda @ B_1
from numpy.linalg import inv
B      = vectors
Lambda = diag(values)

print('Tái tạo ma trận P:\n', np.rint(B @ Lambda @ inv(B)).astype(int))

Tái tạo ma trận B:
 [[ 59  62  59  76  83]
 [ 62 190 113 142 130]
 [ 59 113 134 154 177]
 [ 76 142 154 188 192]
 [ 83 130 177 192 255]]
