## **BT thực hành 2.1.2: Giải hệ PT tuyến tính dựa trên phân rã LU**


> <u>Cập nhật</u>: **11/2024**




In [ ]:
## Thư viện
import numpy        as np
import scipy.linalg as linalg
import warnings
warnings.filterwarnings('ignore')

---
Cho hệ PT tuyến tính: <br/>
    2a + b  + c  = 4<br/>
     a + 3b + 2c = 5<br/>
     a           = 6<br/>   
- Tìm nghiệm dựa trên ma trận nghịch đảo
- Tìm nghiệm bằng hàm lu_solve()
---

In [ ]:
## Ma trận hệ số A và vector hệ số tự do B
A = np.array([[2, 1, 1], [1, 3, 2],[1, 0, 0]])
B = np.array([4, 5, 6])

#### 1. Tìm nghiệm dựa trên <b>ma trận nghịch đảo</b>

In [ ]:
## Cách 1: Nghiệm x = A_1 @ B
x = linalg.inv(A) @ B
x

array([  6.,  15., -23.])

#### 2. Tìm nghiệm bằng hàm <b>lu_solve()</b>

In [ ]:
## B1. Phân rã LU bằng hàm lu_factor()
##    Hàm lu_factor(A) trả về 2 đối tượng:
##       - Ma trận nxn: U + (L - diag(L))
##       - Mảng [n] chứa các chỉ số dòng của I(n) để tạo nên P
LU = linalg.lu_factor(A)
LU

(array([[ 2. ,  1. ,  1. ],
        [ 0.5,  2.5,  1.5],
        [ 0.5, -0.2, -0.2]]),
 array([0, 1, 2], dtype=int32))

In [ ]:
## Ma trận hỗn hợp
LU[0]

array([[ 2. ,  1. ,  1. ],
       [ 0.5,  2.5,  1.5],
       [ 0.5, -0.2, -0.2]])

In [ ]:
## Ma trận U rút trích từ ma trận hỗn hợp
U = np.triu(LU[0])
U

array([[ 2. ,  1. ,  1. ],
       [ 0. ,  2.5,  1.5],
       [ 0. ,  0. , -0.2]])

In [ ]:
## Ma trận L rút trích từ ma trận hỗn hợp
L = LU[0] - U + np.identity(len(B))
L

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  1. ,  0. ],
       [ 0.5, -0.2,  1. ]])

In [ ]:
## Mảng chỉ số để tạo ma trận hoán vị P
LU[1]

array([0, 1, 2], dtype=int32)

In [ ]:
## Hàm tạo ma trận hoán vị P từ pivot = linalg.lu_factor(A)[1]
def permutationMatrix(pivot):
    # Khởi tạo P bằng ma trận đơn vị
    P = np.identity(len(pivot))

    # i: index; r: element
    for i, r in enumerate(pivot):
        # pivot[i] = r
        # Hoán đổi dòng r và dòng pivot[i] của ma trận I

        I = np.identity(len(pivot))

        temp    = I[i, :].copy()
        I[i, :] = I[r, :]
        I[r, :] = temp

        P = P.dot(I)
    return P

In [ ]:
## Ma trận hoán vị P
P = permutationMatrix(LU[1])
P

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## B2. Cách 2: Tìm nghiệm bằng hàm lu_solve()
x = linalg.lu_solve(LU, B)
x

array([  6.,  15., -23.])

In [ ]:
## Cách 3: Dùng solve()
xx = linalg.solve(A, B)
xx

array([  6.,  15., -23.])