## **BT thực hành 2.1.3: Giải hệ PT tuyến tính dựa trên phân rã LU**


> <u>Cập nhật</u>: **11/2024**



In [ ]:
## Thư viện
import numpy      as np
import scipy
import warnings
warnings.filterwarnings('ignore')

from scipy.linalg import lu, inv

In [ ]:
## Ma trận hệ số A và vector hệ số tự do B
A = np.array([[1, 2, 4],
              [3, 8, 14],
              [2, 6, 13]])
B = np.array([3, 13, 4])
print(A)
print(B)

[[ 1  2  4]
 [ 3  8 14]
 [ 2  6 13]]
[ 3 13  4]


In [ ]:
## Tìm nghiệm bằng ma trận nghịch đảo
X = inv(A) @ B
X

array([ 3.,  4., -2.])

In [ ]:
## Áp dụng phân rã LU
P, L, U = lu(A)

In [ ]:
## Kiểm chứng phép phân rã
(P @ L @ U).astype(int)

array([[ 1,  2,  4],
       [ 3,  8, 14],
       [ 2,  6, 13]])

In [ ]:
## B1. Giải L.Y = P.T @ B
Y = inv(L) @ P.T @ B
Y

array([13.        , -4.66666667, -6.        ])

In [ ]:
## B2. Giải U.X = Y
X = inv(U) @ Y
X

array([ 3.,  4., -2.])