## **BT thực hành 2.2.1: Eigenvalues và eigenvectors**

Eigen vector chỉ được phân rã cho **ma trận vuông**


> Cập nhật: **11/2024**



---
### **Yêu cầu 1:**
- Tạo ma trận A(4x4) với các giá trị ngẫu nhiên từ 1 đến 10
- Tìm eigenvalues (lambda[i]) và eigenvectors (v[i]) của A
- Kiểm chứng eigenvector đầu tiên: A.v[0] = lambda[0].v[0] ?
- Nếu bằng nhau thì tái tạo A từ các eigenvectors và eigenvalues
---

In [ ]:
## Thư viện
import numpy      as np
import warnings
warnings.filterwarnings('ignore')

from numpy        import diag
from numpy.linalg import eig, inv

In [ ]:
## Tạo ma trận A(4, 4) với các giá trị ngẫu nhiên từ 1 đến 10
m, n, min, max = 4, 4, 1, 10
A = np.random.randint(min, max + 1, (m, n))
A

array([[ 6,  6,  7,  1],
       [ 3,  3,  8, 10],
       [ 8,  8,  9,  5],
       [ 3,  8,  2,  8]])

In [ ]:
## Tìm eigenvalues và eigenvectors của A -> trả về cả nghiệm thực lẫn nghiệm phức -> luôn đủ n nghiệm
values, vectors = eig(A)

In [ ]:
## Hiển thị kết quả: Trị riêng lambda(r: số thực, i: số phức)
for j in range(len(values)):
    eigenvalue = values[j]

    r = values[j].real
    i = values[j].imag
    print('Eigenvalue[%1d]' %j, '= (%f,' %r, '%f)' %i)

print('\nEigenvectors', vectors.shape, ':\n', vectors)

Eigenvalue[0] = (24.013053, 0.000000)
Eigenvalue[1] = (-4.607116, 0.000000)
Eigenvalue[2] = (-0.728321, 0.000000)
Eigenvalue[3] = (7.322384, 0.000000)

Eigenvectors (4, 4) :
 [[-0.4334975   0.34302585  0.7662847  -0.57818593]
 [-0.49658728 -0.82836912 -0.45867882  0.27101717]
 [-0.63155766  0.12975122 -0.37820347 -0.43246558]
 [-0.40818612  0.42344125  0.24368757  0.63657227]]


In [ ]:
## Kiểm chứng eigenvector đầu tiên: A.v[0] = lambda[0].v[0] ?
v0      = vectors[:, 0]
lambda0 = values[0]     # Chú ý phần số thực
print('A @ v[0]         =', A @ v0)
print('lambda[0] @ v[0] =', lambda0 * v0)

A @ v[0]         = [-10.40959844 -11.92457685 -15.16562781  -9.80179504]
lambda[0] @ v[0] = [-10.40959844 -11.92457685 -15.16562781  -9.80179504]


In [ ]:
## Tái tạo A từ các eigenvectors và eigenvalues:A = B @ Lambda @ B_1
B      = vectors
Lambda = diag(values)

print('\nTái tạo ma trận A:\n', np.rint(B @ Lambda @ inv(B)).astype(int))
# Nhận xét: A có phải là ma trận chéo hóa được ? Có vì ma trận có 4 trị riêng đều là nghiệm thực


Tái tạo ma trận A:
 [[ 6  6  7  1]
 [ 3  3  8 10]
 [ 8  8  9  5]
 [ 3  8  2  8]]


In [ ]:
## Hàm eigvalsh() chỉ trả về eigenvalues (không tạo eigenvectors)
eigenvalues = np.linalg.eigvalsh(A)
print(eigenvalues)

[-6.43714873 -3.38972504  5.90226432 24.92460945]


---
### **Yêu cầu 2:**
- Thực hiện Yêu cầu 1 với ma trận:
       [ 9, 11,  1,  2]
       [ 7,  5, 10,  4]
       [ 2, 10,  1,  1]
       [ 1,  1, 10,  9]
---

In [ ]:
A = np.array([[ 9, 11,  1,  2],
              [ 7,  5, 10,  4],
              [ 2, 10,  1,  1],
              [ 1,  1, 10,  9]])

## Tìm eigenvalues và eigenvectors của A
values, vectors = eig(A)
print('Eigenvalues :', values)
print('Eigenvectors:\n', vectors)

Eigenvalues : [21.34262129 -7.78284152  3.29387086  7.14634936]
Eigenvectors:
 [[-0.61158649 -0.38855303 -0.25905455 -0.37518308]
 [-0.58162527  0.58418387  0.23969712 -0.09183239]
 [-0.36534641 -0.61720767  0.46517086 -0.12275652]
 [-0.392678    0.35610453 -0.81182024  0.9141856 ]]


In [ ]:
## Tái tạo A từ các eigenvectors và eigenvalues:A = B @ Lambda @ B_1
B      = vectors
Lambda = diag(values)
print('\nTái tạo ma trận A:\n', np.rint(B @ Lambda @ inv(B)).astype(int))


Tái tạo ma trận A:
 [[ 9 11  1  2]
 [ 7  5 10  4]
 [ 2 10  1  1]
 [ 1  1 10  9]]
