# **BT thực hành 7.4: Hypothesis Testing**


> Cập nhật: **07/2023**



In [1]:
## Môi trường lập trình
from google.colab import drive
drive.mount("/content/gdrive", force_remount = True)
folder = '/content/gdrive/My Drive/Colab Notebooks/Data Mining/Thống kê suy diễn'

Mounted at /content/gdrive


In [2]:
## Thư viện
import matplotlib.pyplot as plt
import numpy             as np
import pandas            as pd
import scipy.stats       as stats
import seaborn           as sbn
import warnings
warnings.filterwarnings('ignore')

---
## **Yêu cầu 1: Kiểm định Z (trung bình tổng thể)**
---

In [3]:
##-------------------------------------------
## 1.1) Các giả thuyết kiểm định (bên TRÁI)
##      H0: 3 =< Muy
##      Ha: 3  > Muy
##-------------------------------------------
alpha            = .01
confidence_level = (1 - alpha)
Muy0             = 3

In [4]:
## Giả sử tiến hành lấy mẫu kiểm định với:
n, std = 36, 0.18

## Thu được giá trị trung bình của mẫu:
xBar = 2.92

## Tính trị thống kê z
z_stat = (xBar - Muy0) / (std / (n ** .5))
print(f'Trị thống kê z_stat = {z_stat:.2f}')

Trị thống kê z_stat = -2.67


In [5]:
##------------------------------------------------------------------------------
## Hàm xác định giá trị tới hạn (critical value) theo phân phối Z
##     side: left, right, 2-side
##------------------------------------------------------------------------------
def critical_value_Z(side, alpha):
    side = side.lower()

    if (side == 'left'):
        cv = stats.norm.ppf(alpha) # Percent point function (inverse of cdf — percentiles)
    elif (side == 'right'):
        cv = stats.norm.isf(alpha) # Inverse survival function ppf(1 - alpha)
    else:
        cv = abs(critical_value_Z('left', 1 - (alpha / 2)))

    return cv

In [6]:
## Xác định giá trị tới hạn
cv = critical_value_Z('left', alpha)

## Kết luận cho kiểm định bên TRÁI theo phương pháp TRỊ TỚI HẠN
print(f'Giá trị tới hạn z(alpha = {alpha:.2f}) = {cv:.2f}')
if (z_stat < cv):
    print(f'Trị thống kê z = {z_stat:.2f} nằm trong miền BÁC BỎ H0 ==> ({Muy0} > Muy)')
else:
    print(f'CHẤP NHẬN H0 ==> ({Muy0} =< Muy)')

Giá trị tới hạn z(alpha = 0.01) = -2.33
Trị thống kê z = -2.67 nằm trong miền BÁC BỎ H0 ==> (3 > Muy)


In [8]:
##------------------------------------------------------------------------------
## Hàm xác định trị số p (p-value) của phân phối Z
##     side: left, right, 2-side
##------------------------------------------------------------------------------
def p_value_Z(side, statistic):
    side = side.lower()

    if (side == 'right'):
        p = stats.norm.sf(statistic) # survival function 1 - cdf()
    else:
        p = stats.norm.cdf(statistic)

    return (p)

In [9]:
## Tính trị số p theo phân phối Z
p = p_value_Z('left', z_stat)

## Kết luận cho kiểm định bên TRÁI theo phương pháp trị số p
if (p < alpha):
    print(f'Trị số p = {p:.4f} < {alpha:.4f} nên BÁC BỎ H0 ==> ({Muy0} > Muy)')
else:
    print(f'Trị số p = {p:.4f} >= {alpha:.4f} nên CHẤP NHẬN H0 ==> ({Muy0} =< Muy)')

Trị số p = 0.0038 < 0.0100 nên BÁC BỎ H0 ==> (3 > Muy)


In [10]:
##-------------------------------------------
## 1.2) Các giả thuyết kiểm định (bên PHẢI)
##      H0: Muy =< 77
##      Ha: Muy  > 77
##-------------------------------------------
alpha            = .01
confidence_level = (1 - alpha)
Muy0             = 77

In [11]:
## Giả sử tiến hành lấy mẫu kiểm định với:
n, std = 20, 8

## Thu được giá trị trung bình của mẫu:
xBar = 80

## Tính trị thống kê z
z_stat = (xBar - Muy0) / (std / (n ** .5))
print(f'Trị thống kê z_stat = {z_stat:.2f}')

Trị thống kê z_stat = 1.68


In [12]:
## Xác định giá trị tới hạn
cv = critical_value_Z('right', alpha)

## Kết luận cho kiểm định bên PHẢI theo phương pháp TRỊ TỚI HẠN
print(f'Giá trị tới hạn z(alpha = {alpha:.2f}) = {cv:.2f}')
if (z_stat > cv):
    print(f'Trị thống kê z = {z_stat:.2f} nằm trong miền BÁC BỎ H0 ==> ({Muy0} > Muy)')
else:
    print(f'CHẤP NHẬN H0 ==> ({Muy0} =< Muy)')

Giá trị tới hạn z(alpha = 0.01) = 2.33
CHẤP NHẬN H0 ==> (77 =< Muy)


In [13]:
## Tính trị số p theo phân phối Z
p = p_value_Z('right', z_stat)

## Kết luận cho kiểm định theo phương pháp trị số p
if (p < alpha):
    print(f'Trị số p = {p:.4f} < {alpha:.4f} nên BÁC BỎ H0 ==> ({Muy0} > Muy)')
else:
    print(f'Trị số p = {p:.4f} >= {alpha:.4f} nên CHẤP NHẬN H0 ==> ({Muy0} =< Muy)')

Trị số p = 0.0468 >= 0.0100 nên CHẤP NHẬN H0 ==> (77 =< Muy)


---
## **Yêu cầu 2: Kiểm định T (trung bình tổng thể)**
---

In [14]:
##-------------------------------------------
## 2.1) Các giả thuyết kiểm định
##      H0: Muy =< 7
##      Ha: Muy  > 7
##-------------------------------------------
alpha            = .05
confidence_level = (1 - alpha)
Muy0             = 7

In [15]:
## Giả sử tiến hành lấy mẫu kiểm định với:
n, df = 60, 59

## Thu được giá trị trung bình và độ lệch chuẩn của mẫu:
xBar, std = 7.25, 1.052

## Tính trị thống kê z
t_stat = (xBar - Muy0) / (std / (n ** .5))
print(f'Trị thống kê t_stat = {t_stat:.2f}')

Trị thống kê t_stat = 1.84


In [16]:
##------------------------------------------------------------------------------
## Hàm xác định giá trị tới hạn (critical value) theo phân phối T
##     side: left, right, 2-side
##------------------------------------------------------------------------------
def critical_value_T(side, alpha, df):
    side = side.lower()

    if (side == 'left'):
        cv = stats.t.ppf(1 - alpha, df)
    elif (side == 'right'):
        cv = stats.t.isf(alpha, df)
    else:
        cv = abs(critical_value_T('left', 1 - (alpha / 2), df))
    return cv

In [17]:
## Xác định giá trị tới hạn theo phân phối T
cv = critical_value_T('right', alpha, df)

## Kết luận cho kiểm định bên PHẢI theo phương pháp TRỊ TỚI HẠN
print(f'Giá trị tới hạn z(alpha = {alpha:.2f}) = {cv:.2f}')
if (t_stat > cv):
    print(f'Trị thống kê t = {t_stat:.2f} nằm trong miền BÁC BỎ H0 ==> ({Muy0} > Muy)')
else:
    print(f'CHẤP NHẬN H0 ==> ({Muy0} =< Muy)')

Giá trị tới hạn z(alpha = 0.05) = 1.67
Trị thống kê t = 1.84 nằm trong miền BÁC BỎ H0 ==> (7 > Muy)


In [18]:
##------------------------------------------------------------------------------
## Hàm xác định trị số p (p-value) theo phân phối T
##     side: left, right, 2-side
##------------------------------------------------------------------------------
def p_value_T(side, statistics, df):
    side = side.lower()

    if (side == 'right'):
        p = stats.t.sf(statistics, df) # survival function
    else:
        p = stats.t.cdf(statistics, df)

    return (p)

In [19]:
## Tính trị số p theo phân phối T
p = p_value_T('right', t_stat, df)

## Kết luận cho kiểm định theo phương pháp trị số p
if (p < alpha):
    print(f'Trị số p = {p:.4f} < {alpha:.4f} nên BÁC BỎ H0 ==> ({Muy0} > Muy)')
else:
    print(f'Trị số p = {p:.4f} >= {alpha:.4f} nên CHẤP NHẬN H0 ==> ({Muy0} =< Muy)')

Trị số p = 0.0353 < 0.0500 nên BÁC BỎ H0 ==> (7 > Muy)


In [20]:
##-------------------------------------------
## 2.2) Các giả thuyết kiểm định
##      H0: 65 =< Muy
##      Ha: 65  > Muy
##-------------------------------------------
alpha            = .01
confidence_level = (1 - alpha)
Muy0             = 65

In [21]:
## Giả sử tiến hành lấy mẫu kiểm định với:
n, df = 21, 20

## Thu được giá trị trung bình và độ lệch chuẩn của mẫu:
xBar, std = 62.5, 3

## Tính trị thống kê z
t_stat = (xBar - Muy0) / (std / (n ** .5))
print(f'Trị thống kê t_stat = {t_stat:.2f}')

Trị thống kê t_stat = -3.82


In [22]:
## Tính trị số p theo phân phối T
p = p_value_T('left', t_stat, df)

## Kết luận cho kiểm định theo phương pháp trị số p
if (p < alpha):
    print(f'Trị số p = {p:.4f} < {alpha:.4f} nên BÁC BỎ H0 ==> ({Muy0} > Muy)')
else:
    print(f'Trị số p = {p:.4f} >= {alpha:.4f} nên CHẤP NHẬN H0 ==> ({Muy0} =< Muy)')

Trị số p = 0.0005 < 0.0100 nên BÁC BỎ H0 ==> (65 > Muy)


---
**Kiểm định giả thuyết** ⇔ Kiểu định xem hai biến có tương quan không
* Nếu có tương quan: trung bình xấp xỉ nhau → khi phân tích, ta có thể bỏ 01 trong 02 cái
* Nếu không tương quan (độc lập) trung bình chênh lệch nhau → khi phân tích, bắt buộc phải giữ cả hai cái

---
## **Yêu cầu 3: Kiểm định T - 2 mẫu ĐỘC LẬP**
Hai tập tin life_batteries.txt và life_batteries_2.txt lưu trữ 2 mẫu dữ liệu độc lập.
1. Đọc 2 mẫu dữ liệu vào 2 biến life1_array và life2_array.
2. Áp dụng t-test để kiểm định H0: 'Giá trị trung bình bằng nhau' với alpha = 0.05.
---


In [23]:
## 1. Đọc các tập tin dữ liệu.
f = open(folder + "/life_batteries.txt", "r")

## Nội dung tập tin
content     = f.read()

life1       = content.split() # hàm split() rút trích các terms trong chuỗi
f.close()

life1       = list(map(int, life1))  # chuyển sang list()
life1_array = np.array(life1)
life1_array

array([130, 145, 126, 146, 164, 130, 132, 152, 145, 129, 133, 155, 140,
       127, 139, 137, 131, 126, 145, 148, 125, 132, 126, 126, 126, 135,
       131, 129, 147, 136, 129, 136, 156, 146, 130, 146, 132, 142, 132,
       132])

In [24]:
## Tạo life2_array từ nội dung tập tin.
f = open(folder + "/life_batteries_2.txt", "r")

## Nội dung tập tin
content     = f.read()

life2       = content.split() # hàm split() rút trích các terms trong chuỗi
f.close()

life2       = list(map(int, life2))  # chuyển sang list()
life2_array = np.array(life2)
life2_array

array([134, 130, 140, 151, 143, 134, 136, 144, 150, 135, 160, 141, 143,
       140, 138, 141, 148, 146, 140, 146, 151, 138, 151, 139, 151, 128,
       146, 147, 152, 142, 144, 134, 142, 146, 142, 136, 122, 134, 145,
       147])

In [25]:
## 2. Áp dụng t-test để kiểm định H0: 'Giá trị trung bình bằng nhau' với alpha = 0.05.
##-------------------------------------------
## Các giả thuyết kiểm định
##     H0: Muy[1] =  Muy[2] -> cách sử dụng máy tính và tuổi thọ na ná nhau
##     Ha: Muy[1] <> Muy[2] -> cách sử dụng máy tính và tuổi thọ có ảnh hưởng lẫn nhau
##-------------------------------------------
alpha            = .05
confidence_level = 1 - alpha

In [26]:
## So sánh phương sai 2 mẫu dữ liệu
print(f'Var(life_1) = {life1_array.var(ddof = 1):.2f}; Var(life_2) = {life2_array.var(ddof = 1):.2f}')

Var(life_1) = 95.87; Var(life_2) = 55.20


In [28]:
## Kiểm định T, 2 mẫu độc lập
  ## Khác phương sai (equal_var = False)
  ## Giống phương sai (equal_var = True)
t, p = stats.ttest_ind(life1_array, life2_array, equal_var = False)

## t: trị thống kê; p: trị số p
  ## Nếu dùng trị thống kê t thì phải tính thêm trị tới hạn

  ## Dựa trên trị số p:
    ## Nếu p < alpha: bác bỏ H0
    ## Nếu p >= alpha: không bác bỏ H0

In [29]:
## Kết luận theo phương pháp p-value (trị số p)
if (p < alpha):
    print(f'Trị số p = {p:.4f} < {alpha:.4f} nên bác bỏ H0 ==> Muy[1] <> Muy[2]')
else:
    print(f'Trị số p = {p:.4f} >= {alpha:.4f} KHÔNG bác bỏ H0 ==> Mean_1 = Mean_2')

Trị số p = 0.0109 < 0.0500 nên bác bỏ H0 ==> Muy[1] <> Muy[2]


---
## **Yêu cầu 4: Kiểm định T - 2 mẫu PHỤ THUỘC**
**MẪU PHỤ THUỘC:**
* ***Khi lấy hai giá trị của cùng một đối tượng ⇒ có 2 mẫu phụ thuộc***

* ***Lấy một giá trị của một con người ở hai thời điểm khác nhau ⇒ có 2 mẫu phụ thuộc***

* ***Lấy giá trị từ hai đối tượng có liên quan với nhau ⇒ có 2 mẫu phụ thuộc***

Cho 2 mẫu dữ liệu phụ thuộc nhau như sau:
> np.random.seed(11) <br/>
> before = stats.norm.rvs(scale = 30, loc = 250, size = 100) <br/>
> after  = before + stats.norm.rvs(scale = 5, loc = -1.25, size = 100) <br/>

1.   Tạo dataframe chứa dữ liệu: before, after và change = after - before.
2.   Áp dụng t-test để kiểm định H0: 'Giá trị trung bình bằng nhau' với alpha = 0.05.
---



In [30]:
## 1. Tạo dữ liệu theo yêu cầu của đề bài
np.random.seed(11)
before = stats.norm.rvs(scale = 30, loc = 250, size = 100)          # thời điểm (i)
after  = before + stats.norm.rvs(scale = 5,loc = -1.25, size = 100) # thời điểm (i + 1)
df     = pd.DataFrame({"before": before, "after": after, "change": after - before})
df.head()

before       after    change
0  302.483642  305.605006  3.121364
1  241.417810  240.526071 -0.891739
2  235.463046  226.017788 -9.445258
3  170.400443  165.913930 -4.486513
4  249.751461  252.590309  2.838848

In [31]:
## Một số thống tin thống kê
df.describe()

before       after      change
count  100.000000  100.000000  100.000000
mean   250.345546  249.115171   -1.230375
std     28.132539   28.422183    4.783696
min    170.400443  165.913930  -11.495286
25%    230.421042  229.148236   -4.046211
50%    250.830805  251.134089   -1.413463
75%    270.637145  268.927258    1.738673
max    314.700233  316.720357    9.759282

In [32]:
## 2. Áp dụng t-test để kiểm định H0: 'Giá trị trung bình bằng nhau' với alpha = 0.05.
##------------------------------------------
## Các giả thuyết kiểm định
##    H0: Muy[1] =  Muy[2]
##    Ha: Muy[1] <> Muy[2]
##------------------------------------------
alpha            = .05
confidence_level = (1 - alpha)

In [33]:
## Kiểm định T, 2 mẫu phụ thuộc
t, p = stats.ttest_rel(df.before, df.after)

In [34]:
## Kết luận theo phương pháp p-value (trị số p)
if (p < alpha):
    print(f'Trị số p = {p:.4f} < {alpha:.4f} nên bác bỏ H0 ==> Muy[1] <> Muy[2]')
else:
    print(f'Trị số p = {p:.4f} >= {alpha:.4f} KHÔNG bác bỏ H0 ==> Mean_1 = Mean_2')

Trị số p = 0.0116 < 0.0500 nên bác bỏ H0 ==> Muy[1] <> Muy[2]


---
## **Yêu cầu 5: Chi-squared test**
***Dùng để phân tích hai biến PHÂN LOẠI có tương quan hay độc lập?***

*   **H0: ĐỘC LẬP**
*   **H1: PHỤ THUỘC**

***Bởi vì kiểm định Chi-Squared là dương ⇒ KIỂM ĐỊNH BÊN PHẢI***

> Số liệu thống kê về giới tính và trình độ học vấn được mô tả trong bảng bên dưới. Hãy kiểm định giả thuyết về sự liên quan giữa giới tính và trình độ học vấn.

|Loai|Cao dang|Dai Hoc|Sau dai hoc|
|---|---|---|---|
|Nam|6|35|15|
|Nu|7|31|6|

---

In [35]:
## Bảng dữ liệu
table = [[6, 35, 15], [7,  31,  6]]

In [36]:
##----------------------------------------------------
## Các giả thuyết kiểm định
##    H0: Trình độ và giới tính là ĐỘC LẬP
##    Ha: Trình độ và giới tính là PHỤ THUỘC lẫn nhau
##----------------------------------------------------
alpha            = .05
confidence_level = (1 - alpha)

In [37]:
## Kiểm định Chi-square
stat, p, dof, expected = stats.chi2_contingency(table)

In [41]:
print(f'Trị thống kê: {stat}')
print(f'Giá trị p-value: {p}')
print(f'Bậc tự do: {dof}')
print(f'Giá trị kỳ vọng: {expected}')

Trị thống kê: 2.7764713641337027
Giá trị p-value: 0.2495151405494389
Bậc tự do: 2
Giá trị kỳ vọng: [[ 7.28 36.96 11.76]
 [ 5.72 29.04  9.24]]


In [38]:
## Kết luận theo phương pháp p-value (trị số p)
if (p < alpha):
    print(f'Trị số p = {p:.4f} < {alpha:.4f} nên bác bỏ H0 ==> (trình độ, giới tính) PHỤ THUỘC')
else:
    print(f'Trị số p = {p:.4f} >= {alpha:.4f} KHÔNG bác bỏ H0 ==> (trình độ, giới tính) ĐỘC LẬP')

Trị số p = 0.2495 >= 0.0500 KHÔNG bác bỏ H0 ==> (trình độ, giới tính) ĐỘC LẬP
